Sh/bcloud 8536 chat version labels
getbraincloud/examples-unity pull request #178
Opened 2024-06-24 18:20 UTC by spencerh-bitheads

Added second version label, added readme and screenshot, fixed softlock

2024-06-24 19:42 UTC, jo-codegirl requested changes

2024-06-24 19:42 UTC, jo-codegirl commented on BCChat/Assets/App/Scripts/VersionSetter.cs
v taken out of $"v{BrainCloud.Version.GetVersion()}" - is this intentional?

2024-06-24 19:47 UTC, spencerh-bitheads commented on BCChat/Assets/App/Scripts/VersionSetter.cs
Intentional. I can quickly change it if needed. I think it looks cleaner without the v.

2024-07-08 18:08 UTC, bitheadCody approved these changes

2024-07-08 18:08 UTC, nick-bithead approved these changes

2024-07-08 19:03 UTC, merged